In [2]:
import tensorflow as tf
import numpy as np

# Constants

In [7]:
a = tf.constant(1)
b = tf.constant(2)
c = tf.add(a,b)

In [8]:
with tf.Session() as sess:
    result = sess.run(c)

print(type(result))
print(result)

<class 'numpy.int32'>
3


In [9]:
print(type(a))
print(type(b))
print(type(c))
print(result.shape, result.dtype)

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
() int32


In [10]:
a = [1,'a']
_a = np.array([1, "a"])
_b = np.array([1,2], dtype=np.int64)

print(type(a))
print(type(_a), _a.shape, _a.dtype)
print(type(_b), _b.shape, _b.dtype)

<class 'list'>
<class 'numpy.ndarray'> (2,) <U21
<class 'numpy.ndarray'> (2,) int64


# Array

In [ ]:
_b = np.array([1, "a"], dtype=np.int32) # error

In [12]:
_x = [[1,2], [3,4]]
x = tf.convert_to_tensor(_x)
with tf.Session() as sess:
    # sess.run(pl_) # error occur
    print(sess.run(x))

[[1 2]
 [3 4]]


# Placeholder

In [3]:
pl_ = tf.placeholder(tf.float32) # any shape
pl0 = tf.placeholder(tf.float32, []) # 0-D
pl1 = tf.placeholder(tf.int32, [None]) # 1-D
pl2 = tf.placeholder(tf.int32, [None, 3]) #2-D

In [53]:
with tf.Session() as sess:
    # 01. error occur : placeholder is empty
    # sess.run(pl1) 
    
    # 02. assign the ops
    y = pl1 + 1  # same opertion (override operation)
    # y = tf.add(pl1, 1)
  
    # 03. calculate the operations and dictionary assignment
    x = np.array([1,2,3], dtype=np.int32)
    print(sess.run(y, {pl1 : x}))

[2 3 4]


#  Zero, Ones

In [32]:
_ones = np.ones([2,3])
_ones

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [33]:
zero = np.zeros([2,2])
_x = np.array([[1,2], [3,4]])
_zero = np.zeros_like(_x)

print(zero)
print(_zero)

[[ 0.  0.]
 [ 0.  0.]]
[[0 0]
 [0 0]]


In [34]:
X = tf.zeros([2,3])
with tf.Session() as sess:
    print(X.eval())
    result = sess.run(X)

print(X)    
print(result)

# print(X.eval())  # error : sessions needed

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
Tensor("zeros_1:0", shape=(2, 3), dtype=float32)
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


# Vectors

In [35]:
_v1 = np.linspace(0, 100, 5)
_v2 = np.arange(0, 10, 2)
_v3 = np.zeros([3,2], dtype=np.int32)
_v3.fill(5)
print(_v1)
print(_v2)
print(_v3)

[   0.   25.   50.   75.  100.]
[0 2 4 6 8]
[[5 5]
 [5 5]
 [5 5]]


In [36]:
v1 = tf.linspace(0., 10, 5)
# v1 = tf.linspace(0, 10, 5) # error : type error

v2 = tf.range(0, 10, 2)
v3 = tf.fill([3,2], 5)

In [37]:
with tf.Session() as _:
    print(v1.eval())
    print(v2.eval())
    print(v3.eval())

[  0.    2.5   5.    7.5  10. ]
[0 2 4 6 8]
[[5 5]
 [5 5]
 [5 5]]


# Random

In [39]:
_x = np.random.uniform(0, 1, [3,2])
print(_x)

[[ 0.41526711  0.65640853]
 [ 0.86275865  0.77598978]
 [ 0.6206108   0.96859151]]


### Jupyter help

In [40]:
np.random.uniform?

In [41]:
np.random.normal(0, 1, [3,2])

array([[-0.73970858, -0.08029971],
       [-0.94494442, -1.18914113],
       [ 0.96488233,  2.02769975]])

In [42]:
x1 = tf.random_uniform([3,2], 0, 1)
x2 = tf.random_normal([3,2],0, 1)

In [44]:
with tf.Session() as _:
    print(x1.eval())
    print(x2.eval())

[[ 0.27832341  0.26609826]
 [ 0.63762224  0.7535435 ]
 [ 0.19322598  0.64275217]]
[[ 0.2721779   0.59077054]
 [ 0.02874213  0.07004149]
 [-0.51612157 -0.47622034]]
